const mongoose = require ("mongoose");
const ResumeSchema = new mongoose.Schema(
    {
        userId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
            required:true,
        },
        title:{
            type:String,
            required:true,
        },
        thumbnailLink:{
            type:String,
            required:true,
        },
        template:{
            theme:string,
            colorPalette:string,
        },
        profileInfo:{
            profilePreviewUrl:string,
            fullName:string,
            designation:string,
            summary:string,
        },
        contactInfo:{
            email:string,
            phone:string,
            location:string,
            linkedin:string,
            github:string,
            website:string,
        },
        workExperience:[
            {
                companyName:string,
                role:string,
                startDate:string,
                endDate:string,
                description:string,
            },
        ],
        education:[
            {
                degree:string,
                institution:string,
                startDate:string,
                endDate:string,
            },
        ],
        skills:[
            {
                name:string,
                progress:string,
                github:string,
                liveDemo:string,
            },
        ],
        certifications:[
            {
                name:string,
                issuer:string,
                year:string,
            },
        ],
        languages:[
            {
                name:string,
                progress:string,
            },
        ],
        interests:[String],
    },
    {timestamps:{createdAt:"createdAt",updatedAt:"updatedAt"},}
); 

module.exports= mongoose.model("Resume",ResumeSchema);