const mongoose = require ("mongoose");
const ResumeSchema = new mongoose.Schema(
    {
        userId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
            required:true,
        },
        title:{
            type:String,
            required:true,
        },
        thumbnailLink:{
            type:String,
            required:true,
        },
        template:{
            theme:String,
            colorPalette:String,
        },
        profileInfo:{
            profilePreviewUrl:String,
            fullName:String,
            designation:String,
            summary:String,
        },
        contactInfo:{
            email:String,
            phone:String,
            location:String,
            linkedin:String,
            github:String,
            website:String,
        },
        workExperience:[
            {
                companyName:String,
                role:String,
                startDate:String,
                endDate:String,
                description:String,
            },
        ],
        education:[
            {
                degree:String,
                institution:String,
                startDate:String,
                endDate:String,
            },
        ],
        skills:[
            {
                name:String,
                progress:String,
                github:String,
                liveDemo:String,
            },
        ],
        certifications:[
            {
                name:String,
                issuer:String,
                year:String,
            },
        ],
        languages:[
            {
                name:String,
                progress:String,
            },
        ],
        interests:[String],
    },
    {timestamps:{createdAt:"createdAt",updatedAt:"updatedAt"},}
); 

module.exports= mongoose.model("Resume",ResumeSchema);